language: node_js
node_js:
  - 0.12
branches:
  only:
    - master
env:
  global:
    - secure: gw0E7DKPKkhoIlAOhgw+m+b+lYC7lEaKUe0XrlbTjBCSS98+vJsoJGw55UOKgSALBFlP0ULjOOn+0EtSQ0Ffm10jCLdnizgLzEhO3SGymdxqmQMVPAoitIbarGo4K9On6QYZt5UE/FUvS9Ce3WBtZE5HySn8GEJznPeTzchyh38odF1JglOzij8rRI+/OZfYAoN6+fjN9NTIRixVpEHPTwueBsuCVGjKqPDVzeal7rElfGk9bJOkliV0bfLmdbp9U9P/iDZ/Byr4FvE53qx0Pqhyq3iW6mCLgao/+6kFOvJVw3vKBwYvuNju/GgoEWzUv7XmMYwv/3jvxgCYUBIID4KaBW9BaLgkTrq0+dxfgcjY3rk+6P0lMipSUWbcN1aH7ou6mo0X6aUfFXcqUlrcS11vItUcieIYLrA5AVxm5760FKHc1bT5+L2egDUxnfsTCsrM/NOApM0VgJr1zpL6Pae1uwneFIINHO4FNMCPte7thUDvZu2t5O0KSVXJ9S6dZRLptkYKdoVynHmEcbkc/dxxCxaa+/gMChRP5X8ZKqNRWFZmbCZ3P+sSdCHVdh1cZInaKKoIDvbJrxatWgM0gjDcv1z42jwSeg9jsdf8eTACIlMPTqm019sm6ESJtiHf0Sy0LFAviGHPjNLfHjoFNexIc1T4tyDbuJ2n5pxoWRY=
    - secure: aSyppmIteT2xzwv8ShC3sOExTU/0RYTj12iO2DX5YWD0GGTvx33FhiYEbgAwxqscXmvolULZR6zhCRHB3+g0uukG5BcrUhB7v6g96P/eGsjpdPw0JJETq7aJNTOed3aGJpiAfeuyMrcdBXcnkQr6AbNfVqU0RiyA9rTJi3cr2QL9OD832SlfY87OBrm6j+7gjwuO6Ug7GAiZEPlE6gnAYHBSE/YbO91g7kSJrhypOv25gpThwWDOgYbg6BD8VLnl3G9jYzVTH3Qhz8iERg80bT+vP8lFoFS7f4M1G6ErSPH5PdzL8ipV+g08y3XIfkdMWA5X4lrQl4d3DmeT6WmjVZ6GtTY5h3H4bh+cVYQ31yfi1PDgXr3PXnwxUrQoz0dD8D14I2O1N9gc5THcH7Bt/FLWoQnxf4PQPL9IGFCb2us/HKUUYHKdL6sKVf6HXLXHOzoArPm1GpYpApbQYIzviHXCVoRr/S0DSALwOcGEjRnf9wW9NN/vJcwHRzxRbHZVuwkVMH5KFETsSFdxUu772wZmFQP72bG3WGX9S1Syv0GK5iZjpSburhKHtNgecvYX1QTcvx6z33HvBrIhjU1rgi98p2w0zdfaIRZPRj33/kvM1WzvCYhjBY4b9wL4Ap5efuNGe77toxWaJxdZ/bKCcj+6KCWU71/+AykmeNKue8A=
addons:
  sauce_connect: true
